# Source: https://github.com/boostorg/hana/blob/master/.travis.yml

# Use distribution Ubuntu 18.04 Bionic
dist: bionic

# Use C++ build environment.
language: cpp

# Protobuf requires g++ (see https://github.com/google/protobuf/blob/master/src/README.md)
compiler:
    - gcc

# Cache dependencies to speed up the build.
cache:
    directories:
        - ${HOME}/deps/cmake
        - ${HOME}/deps/protobuf
#        - ${HOME}/deps/proto2cpp

# Handle dependencies in separate directory.
before_install:
    - TESTINST_DIR="${HOME}/dummy"
    - mkdir -p "${TESTINST_DIR}"
    - DEPS_DIR="${HOME}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

# Install necessary packages.
install:
    # Install a recent version of CMake
    - |
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        if [ ! -f ${DEPS_DIR}/cmake/bin/cmake ] ; then mkdir -p cmake ; travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake ; fi
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Install a recent version of the Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then mkdir -p protobuf ; travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf ; cd protobuf ; ./configure --prefix=${DEPS_DIR}/protobuf/install ; make ; make install ; fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}

    # Install proto2cpp for doxygen
    - |
        PROTO2CPP_URL="https://github.com/OpenSimulationInterface/proto2cpp.git"
        if [ ! -f ${DEPS_DIR}/proto2cpp ] ; then mkdir -p proto2cpp ; git clone ${PROTO2CPP_URL} ${DEPS_DIR}/proto2cpp ; fi

# Environment variables.
env:
  global:
    - GH_REPO_ORG=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 1`
    - GH_REPO_NAME=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
    - GH_REPO_REF="github.com/$GH_REPO_ORG/$GH_REPO_NAME.git"

# Addons necessary for documentation.
addons:
    apt:
        packages:
        - doxygen
        - doxygen-doc
        - doxygen-latex
        - doxygen-gui
        - graphviz
        - python3-setuptools


jobs:
  include:
    # Run the build script and generate documentation.
    - stage: test OSI protobuf

      name: 'Test protobuf 2.6.1 syntax'
      script:
          - cd "${TRAVIS_BUILD_DIR}"
          - mkdir -p build
          - cd build
          - cmake -D CMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install -D CMAKE_INSTALL_PREFIX:PATH=${TESTINST_DIR} ..
          - cmake --build .
          - cd ..
          - python3 setup.py build
          - python3 setup.py sdist
          - cd build
          - cmake --build . --target install
          - cd ..
          - cp VERSION VERSION.SAVED
          - echo "" >> VERSION
          - echo "VERSION_PATCH = \"GitHub_MasterBranch\"" >> VERSION
          - cd build
          - cmake -D FILTER_PROTO2CPP_PY_PATH=${DEPS_DIR}/proto2cpp ..
          - echo "EXCLUDE_PATTERNS = */osi3/*" >> Doxyfile
          - echo "GENERATE_TREEVIEW = YES" >> Doxyfile
          - doxygen
          - cd ..
          - python3 -m unittest discover tests

    - script:
          - cd "${TRAVIS_BUILD_DIR}"
          - bash convert-to-proto3.sh
          - rm *.pb2
          - mkdir -p build
          - cd build
          - cmake -D CMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install -D CMAKE_INSTALL_PREFIX:PATH=${TESTINST_DIR} ..
          - cmake --build .
          - cd ..
          - python3 setup.py build
          - python3 setup.py sdist
          - cd build
          - cmake --build . --target install
          - cd ..
          - cp VERSION VERSION.SAVED
          - echo "" >> VERSION
          - echo "VERSION_PATCH = \"GitHub_MasterBranch\"" >> VERSION
          - cd build
          - cmake -D FILTER_PROTO2CPP_PY_PATH=${DEPS_DIR}/proto2cpp ..
          - echo "EXCLUDE_PATTERNS = */osi3/*" >> Doxyfile
          - echo "GENERATE_TREEVIEW = YES" >> Doxyfile
          - doxygen
          - cd ..
          - python3 -m unittest discover tests
      name: 'Test protobuf 3.0.0 syntax'

    - stage: deploy
      script:
          - cd "${TRAVIS_BUILD_DIR}"
          - mkdir -p build
          - cd build
          - cmake -D CMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install -D CMAKE_INSTALL_PREFIX:PATH=${TESTINST_DIR} ..
          - cmake --build .
          - cd ..
          - python3 setup.py build
          - python3 setup.py sdist
          - cd build
          - cmake --build . --target install
          - cd ..
          - cp VERSION VERSION.SAVED
          - echo "" >> VERSION
          - echo "VERSION_PATCH = \"GitHub_MasterBranch\"" >> VERSION
          - cd build
          - cmake -D FILTER_PROTO2CPP_PY_PATH=${DEPS_DIR}/proto2cpp ..
          - echo "EXCLUDE_PATTERNS = */osi3/*" >> Doxyfile
          - echo "GENERATE_TREEVIEW = YES" >> Doxyfile
          - doxygen
          - cd ..
          - python3 -m unittest discover tests

    # Deploy the documentation on github (only for master branch).
      deploy:
          provider: pages
          skip_cleanup: true
          local_dir: doc/html
          keep-history: true
          github_token: ${GH_REPO_TOKEN}
          on:
              branch: master
